// <auto-generated />
namespace SW_attendance_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FixTimeInLecture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixTimeInLecture));
        
        string IMigrationMetadata.Id
        {
            get { return "201611062008091_FixTimeInLecture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
