// <auto-generated />
namespace SW_attendance_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CoursesForStudents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CoursesForStudents));
        
        string IMigrationMetadata.Id
        {
            get { return "201611061708535_CoursesForStudents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
